name: mental_health_care_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.4
  get: ^4.7.2
  cloud_firestore: ^5.6.8
  url_launcher: ^6.3.1
  audioplayers: ^6.4.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:      
  android: true
  ios: true
  image_path: "assets/images/icon_app.png"

  
flutter:
  uses-material-design: true
  assets:
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/Meditation.png
    - assets/images/profile_picture.jpg

    - assets/images/logo_white.png
    - assets/images/Mindcare logo.png
    - assets/images/onboarding_image.png
    - assets/images/google.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


    - assets/images/MindcareLogo.png
    - assets/images/anxiety.png
    - assets/images/depression.png
    - assets/images/guidedmeditation.png
    - assets/images/selflove.png
    - assets/images/stressmanagement.png
    - assets/images/calm.png
    - assets/images/practice.png
    - assets/images/affirments.png
    - assets/images/sm1.png
    - assets/images/sm2.png
    - assets/images/sm3.png
    - assets/images/calmbreathing.png
    - assets/images/d1.png
    - assets/images/d2.png
    - assets/images/d3.png
    - assets/images/mood.png
    - assets/images/deptest.png
    - assets/images/Mindcare_logo.png
    - assets/images/icon_app.png

    - assets/music/abc.mp3
    - assets/music/abcd.mp3
    - assets/music/abcde.mp3

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  


