name: mental_health_care_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/Meditation.png
    - assets/images/profile_picture.jpg
    - assets/images/MindcareLogo.png
    - assets/images/anxiety.png
    - assets/images/depression.png
    - assets/images/guidedmeditation.png
    - assets/images/selflove.png
    - assets/images/stressmanagement.png
    - assets/images/calm.png
    - assets/images/practice.png
    - assets/images/affirments.png
    - assets/images/sm1.png
    - assets/images/sm2.png
    - assets/images/sm3.png
    - assets/images/calmbreathing.png
    - assets/images/d1.png
    - assets/images/d2.png
    - assets/images/d3.png
    - assets/images/mood.png




